import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:provider/provider.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import 'package:animate_do/animate_do.dart';
import '../config/theme.dart';
import '../services/translation_service.dart';

/// Stores FIR draft data for history
class FirHistoryItem {
  final String draft;
  final List<String> sections;
  final String complainantName;
  final DateTime createdAt;
  final String firNo;

  FirHistoryItem({
    required this.draft,
    required this.sections,
    required this.complainantName,
    required this.createdAt,
    required this.firNo,
  });
}

/// Global in-memory history store
class FirHistoryStore {
  static final FirHistoryStore _instance = FirHistoryStore._();
  factory FirHistoryStore() => _instance;
  FirHistoryStore._();

  final List<FirHistoryItem> items = [];

  void add(FirHistoryItem item) {
    items.insert(0, item);
  }
}

class FirDraftScreen extends StatefulWidget {
  final String draft;
  final List<String> sections;
  final String complainantName;
  final bool fromHistory;

  const FirDraftScreen({
    super.key,
    required this.draft,
    this.sections = const [],
    this.complainantName = '',
    this.fromHistory = false,
  });

  @override
  State<FirDraftScreen> createState() => _FirDraftScreenState();
}

class _FirDraftScreenState extends State<FirDraftScreen> {
  @override
  void initState() {
    super.initState();
    // Only save to history when creating a new draft, not when viewing from history
    if (!widget.fromHistory) {
      _saveToHistory();
    }
  }

  void _saveToHistory() {
    final firNoMatch = RegExp(r'FIR No\.\s*:\s*(\S+)').firstMatch(widget.draft);
    FirHistoryStore().add(FirHistoryItem(
      draft: widget.draft,
      sections: widget.sections,
      complainantName: widget.complainantName.isNotEmpty
          ? widget.complainantName
          : 'Unknown',
      createdAt: DateTime.now(),
      firNo: firNoMatch?.group(1) ??
          'FIR-${DateTime.now().millisecondsSinceEpoch}',
    ));
  }

  Future<void> _exportPdf(BuildContext context) async {
    final tr = Provider.of<TranslationService>(context, listen: false);
    final pdf = pw.Document();

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(40),
        header: (pw.Context ctx) => pw.Column(
          crossAxisAlignment: pw.CrossAxisAlignment.start,
          children: [
            pw.Row(
              mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
              children: [
                pw.Text('VIDHANA AI',
                    style: pw.TextStyle(
                        fontSize: 18, fontWeight: pw.FontWeight.bold)),
                pw.Text('FIRST INFORMATION REPORT',
                    style: pw.TextStyle(
                        fontSize: 14, fontWeight: pw.FontWeight.bold)),
              ],
            ),
            pw.Divider(thickness: 2),
            pw.SizedBox(height: 8),
          ],
        ),
        build: (pw.Context ctx) => [
          pw.Text(widget.draft, style: const pw.TextStyle(fontSize: 11)),
        ],
        footer: (pw.Context ctx) => pw.Container(
          alignment: pw.Alignment.centerRight,
          child: pw.Text(
            'Generated by Vidhana AI  •  Page ${ctx.pageNumber}/${ctx.pagesCount}',
            style: const pw.TextStyle(fontSize: 8, color: PdfColors.grey600),
          ),
        ),
      ),
    );

    await Printing.layoutPdf(onLayout: (format) => pdf.save());

    if (context.mounted) {
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(content: Text(tr.t('pdf_generated'))),
      );
    }
  }

  @override
  Widget build(BuildContext context) {
    final tr = Provider.of<TranslationService>(context);

    return Scaffold(
      appBar: AppBar(
        title: Text(tr.t('fir_draft')),
        actions: [
          IconButton(
            icon: const Icon(Icons.copy_rounded),
            tooltip: tr.t('copy_clipboard'),
            onPressed: () {
              Clipboard.setData(ClipboardData(text: widget.draft));
              ScaffoldMessenger.of(context).showSnackBar(
                SnackBar(content: Text(tr.t('draft_copied'))),
              );
            },
          ),
          IconButton(
            icon: const Icon(Icons.picture_as_pdf_rounded,
                color: AppColors.error),
            tooltip: tr.t('download_pdf'),
            onPressed: () => _exportPdf(context),
          ),
        ],
      ),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(16),
        child: FadeInUp(
          child: Container(
            padding: const EdgeInsets.all(16),
            decoration: AppTheme.glassCard(opacity: 0.06),
            child: SelectableText(
              widget.draft,
              style: const TextStyle(
                fontFamily: 'monospace',
                fontSize: 12,
                height: 1.6,
                color: AppColors.textPrimary,
              ),
            ),
          ),
        ),
      ),
      floatingActionButton: FloatingActionButton.extended(
        onPressed: () => Navigator.popUntil(context, (r) => r.isFirst),
        backgroundColor: AppColors.accent,
        foregroundColor: AppColors.primary,
        icon: const Icon(Icons.home_rounded),
        label: Text(tr.t('new_prediction')),
      ),
    );
  }
}
